
spring:
    session:
        store-type: none
#spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3308/ba?useUnicode=yes&characterEncoding=UTF-8
#        platform: mysql
#        username: ba
#        password: ba
#        continue-on-error: true
#        tomcat:
#            test-while-idle: true
#            test-on-borrow: true
#            validation-query: SELECT 1
#            validation-interval: 60000